### ISSUE TITLE
does not overwrite user.token when it is already present in original config

### ISSUE THREAD

**Issue by czchen** [rafi/kubectl-config-import#1]
When using `kubectl config-import -f $new_config`, if `user.token` in original config already exists, it will not be overwritten by `$new_config`.

In our scenario, the kubeconfig has expiration and we need to download new kubeconfig to replace the old one. However, since `user.token` is not overwritten, we need to first remove the old configure using editor, and then `kubectl config-import ...` to import new configuration. It would be better if `kubectl config-import -f $new_config` can just overwriite everything.

**Comment by rafi** [comment]
Yes, it makes sense to overwrite with provided file. Just released [v0.6.7](https://github.com/rafi/kubectl-config-import/releases/tag/v0.6.7) with this change. Let me know if that works for you.

**Comment by czchen** [comment]
It is fixed, thanks for the help.
